[package]
name = "heimdall-lib"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
fern = "0.6.2"
humantime = "2.1.0"
melody_compiler = "0.18.1"
lazy_static = "1.4.0"
regex = "1.8.3"
